<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\MarketAPI.Communication\MarketAPI.Communication.csproj" />
    <ProjectReference Include="..\..\Shared\MarketAPI.Exception\MarketAPI.Exception.csproj" />
    <ProjectReference Include="..\MarketAPI.Domain\MarketAPI.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Mapster" Version="10.0.8-pre06" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="11.0.0-preview.4.26230.115" />
  </ItemGroup>

</Project>
