services:
  marketapi.api:
    image: marketapi.api
    build:
      context: .
      dockerfile: src/Backend/MarketAPI.Api/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
      - redis
    ports:
      - "8080:8080"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: marketapi-sqlserver
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your@Password123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: marketapi-rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:alpine
    container_name: marketapi-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  sqlserver_data: {}
  redis_data: {}